version: "3.8"
services:

  no_waste:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    image: no_waste:no_waste
    container_name: no_waste_container
    networks:
      default:
        aliases:
          - no-waste

  db:
    image: postgres:14.5
    volumes:
      - ./data/db:/var/lib/postgressql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: no_waste_db
    ports:
      - "5432:5432"
    networks:
      default:

networks:
  default:
    driver: bridge

