# Generated by Django 4.0.4 on 2022-06-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_pt', models.CharField(max_length=200)),
                ('picture_url', models.URLField()),
                ('ingredients', models.CharField(max_length=500)),
                ('ingredients_pt', models.CharField(max_length=500)),
                ('carbs', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('calories', models.FloatField()),
                ('source_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=500, unique=True)),
                ('recipes', models.ManyToManyField(related_name='recipes', to='recipes.recipe')),
            ],
            options={
                'verbose_name_plural': 'Search queries',
            },
        ),
        migrations.CreateModel(
            name='MissingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_ingredient_count', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.recipe')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query', to='recipes.searchquery')),
            ],
        ),
    ]
