# Generated by Django 4.0.4 on 2022-07-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_pt', models.CharField(max_length=200)),
                ('picture_url', models.URLField()),
                ('ingredients', models.CharField(max_length=500)),
                ('ingredients_pt', models.CharField(max_length=500)),
                ('carbs', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('calories', models.FloatField()),
                ('source_url', models.URLField()),
                ('missing_ingredients_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=500, unique=True)),
                ('recipes', models.ManyToManyField(related_name='recipes', to='recipes.recipe')),
            ],
            options={
                'verbose_name_plural': 'Search queries',
            },
        ),
    ]
