# Generated by Django 4.0.4 on 2022-06-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_missingingredients_searchquery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='search_query',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
