# Generated by Django 4.0.4 on 2022-06-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_searchquery_search_query'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissingIngredients',
            new_name='MissingIngredient',
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'verbose_name_plural': 'Search queries'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='sourceurl',
            new_name='source_url',
        ),
    ]
