# Generated by Django 4.0.4 on 2022-06-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_missingingredients_missingingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_pt',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_pt',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
