# Generated by Django 4.0.4 on 2022-06-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_ingredients_pt_recipe_title_pt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='recipes',
            field=models.ManyToManyField(related_name='recipes', to='recipes.recipe'),
        ),
    ]
