# Generated by Django 4.0.4 on 2022-06-12 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_searchquery_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingingredient',
            name='search_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query', to='recipes.searchquery'),
        ),
    ]
