# Generated by Django 4.0.4 on 2022-06-12 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_missingingredient_search_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.recipe'),
        ),
    ]
