# Generated by Django 4.0.4 on 2022-06-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_missingingredient_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingingredient',
            old_name='count',
            new_name='missing_ingredient_count',
        ),
    ]
